---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-test-restore
  namespace: jenkins
spec:
  storageClassName: rook-ceph-block
  dataSource:
    name: jenkins-snapshot
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
