kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ceph
  namespace: default
spec:
  storageClassName: ceph
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: ceph-pod1
spec:
  containers:
  - name: nginx
    image: nginx:1.14
    volumeMounts:
    - name: ceph
      mountPath: /usr/share/nginx/html
      readOnly: false
  volumes:
  - name: ceph
    persistentVolumeClaim:
      claimName: ceph
