- name: NodeExporterInstall
  hosts: all
  tasks:
  - name: install docker 
    yum: name=docker-ce-18.09.0
    # when: (rpm -qa|grep tree;echo $?)==1
    tags: install
  - name: run node exporter in docker
    shell: docker run -d --name=node-exporter --net="host" --pid="host" -v "/:/host:ro,rslave" quay.io/prometheus/node-exporter --path.rootfs=/host
    tags: run
  # - name: run exxporter in docker
  #   docker_container:
  #     name: node_exporter
  #     image: quay.io/prometheus/node-exporter
  #     network_mode: host 
  #     pid_mode: host
  #     volumes:
  #     - /:/host:ro,rslave
  #     command: --path.rootfs=/host