{
 "title": "Nginx VTS Stats",
 "description": "Show stats from the hnlq715/nginx-vts-exporter.",
 "tags": [
  "prometheus",
  "nginx"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Instance",
    "query": "label_values(nginx_server_bytes, instance)"
   },
   {
    "name": "Host",
    "query": "label_values(nginx_server_bytes{instance=~\"$Instance\"}, host)"
   },
   {
    "name": "Upstream",
    "query": "label_values(nginx_upstream_bytes{instance=~\"$Instance\"}, upstream)"
   }
  ]
 },
 "panels": [
  {
   "title": "Server Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nginx_server_connections{instance=~\"$Instance\", status=~\"active|writing|reading|waiting\"}",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "UV&PV",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "UV",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "cookie.keyword",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      }
     ],
     "timeField": "@timestamp"
    },
    {
     "alias": "PV",
     "bucketAggs": [
      {
       "fake": true,
       "id": "4",
       "query": "*",
       "settings": {
        "filters": [
         {
          "query": "request.keyword=\"/\""
         }
        ]
       },
       "type": "filters"
      },
      {
       "fake": true,
       "field": "request.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Server Requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(nginx_server_requests{instance=~\"$Instance\", code!=\"total\"}[5m])) by (code)",
     "legendFormat": "{{ code }}"
    }
   ]
  },
  {
   "title": "Server Bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(irate(nginx_server_bytes{instance=~\"$Instance\", host=~\"^$Host$\"}[5m])) by (direction)",
     "legendFormat": "{{ direction }}"
    }
   ]
  },
  {
   "title": "Upstream Requests",
   "type": "graph",
   "description": "This one is providing aggregated error codes, but it's still possible to graph these per upstream.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(nginx_upstream_requests{instance=~\"$Instance\", upstream=~\"^$Upstream$\",code!=\"total\"}[5m])) by (code)",
     "legendFormat": "{{ code }}"
    }
   ]
  },
  {
   "title": "Upstream Bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(nginx_upstream_bytes{instance=~\"$Instance\", upstream=~\"^$Upstream$\"}[5m])) by (direction)",
     "legendFormat": "{{ direction }}"
    }
   ]
  },
  {
   "title": "Upstream Backend Response",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(nginx_upstream_responseMsec{instance=~\"$Instance\", upstream=~\"^$Upstream$\"}) by (backend)",
     "legendFormat": "{{ backend }}"
    }
   ]
  }
 ]
}